### PR TITLE
Fix the issue that upgrade service can not upgrade all services

### PR DESCRIPTION
**Pull request by loganhz**
When the number of service is larger then 100, upgrade service can not upgrade all of the services. We need to pass the parameter limit=-1 to get all services back.

https://github.com/rancher/rancher/issues/10258

### CODE REVIEW

**Comment by loganhz** [comment]
@yasker FYI

**Comment by vincent99** [comment]
This is not a fix.  -1 means the largest the server feels like returning, which is a thousand or two.  You need to process the data you got back, see if it's a partial response (`pagination.partial`), and repeat using the `pagination.next` link.

**Comment by loganhz** [comment]
Thanks Vince! PR updated.

**Comment by yasker** [comment]
@vincent99 How does this one look?

**Comment by vincent99** [comment]
This is better in that it will work now... but loading all the pages beforehand and buffering them is sort of a waste of memory (vs processing each page directly as you get it).

**Comment by loganhz** [comment]
@vincent99 @mrajashree  PR updated with the change for processing each page directly.

I think there are 2 selector issues in current version for `upgrade service` and `scale host`.  
I'm not sure if they are expected or not.

Case 1

Only the last label of webhook selector labels will be used. For example, if user sets a webhook with selector labels `foo1=bar1` and `foo=bar`. I think the service which just has one label `foo=bar` should not be upgraded. But it will be upgraded in current version.

Case 2

Selector label without value will not match a label with the same key and arbitrary value. For example, if user  sets a webhook for upgrade service with selector labels `foo`. I think the service which has `foo=bar` should also be upgraded. But it will not be upgraded in current version.

**Comment by vincent99** [comment]
Case 1: I thought they were ORed together, are you saying only the last selector provided is even considered?  Changing multiple labels from being ANDed together instead of ORed seems like a significant breaking change in behavior.

Case 2: Agree that `foo` should match any service that has a label the key `foo` regardless of value.

**Comment by loganhz** [comment]
Thanks Vince.  
I have changed them to be ORed together in this PR.
yes, only the last property (or label) of  `serviceUpgradeConfig. serviceSelector` is considered. For example,  a webhook with selector `a:b` and `c:d` will not upgrade a service with label `a:b`

**Comment by vincent99** [comment]
Sorry, so given what the current behavior is I guess multiple labels should be ANDed together.  The current behavior makes no sense really, but either way switching to either AND or OR is going to change the behavior.

Switching to AND errs on the safe side of not-selecting things you may have wanted, while switching to OR errs on the dangerous side of selecting things you may have not wanted.

Also AND is more useful, because you can already simulate OR by having multiple separate hooks, but you can't create your own AND behavior.

**Comment by yasker** [comment]
@loganhz @vincent99  OK, let's change it to AND. It should be good enough.

**Comment by loganhz** [comment]
Changed to AND :) thanks Vince and Sheng

**Comment by loganhz** [comment]
@yasker updated

**Comment by yasker** [comment]
LGTM. @vincent99 ?

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/10285

**Comment by deniseschannon** [comment]
@loganhz @yasker did we also update for case 2? where if we put in `foo` it would match any labels that have that same key?

**Comment by loganhz** [comment]
@deniseschannon yes, we did

**Comment by loganhz** [comment]
@deniseschannon created an issue for case 2 https://github.com/rancher/rancher/issues/10286

**Comment by cjellick** [comment]
@loganhz thanks for finding and fixing. This really should have been two separate commits, 1 for each bug. But that is not a big deal. No need to change it, just keep it in mind for the future: 1 commit per bug. This makes reverting a change easier.

**Comment by loganhz** [comment]
@cjellick got it! Thanks

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
