### PR TITLE
add Alibaba Cloud Docker Hub webhook support in service upgrade

### PR DESCRIPTION
**Pull request by loganhz**
payload of Alibaba Cloud Docker Hub's webhook is slightly different from Docker Hub.
So I have added an option in UI for it [#9175](https://github.com/rancher/rancher/issues/9175)
PR for UI change is [here](https://github.com/rancher/ui/pull/1241)
image

image

### CODE REVIEW

**Comment by niusmallnan** [comment]
It might be better to use `switch case` here.
Because we might also be compatible with other "dockerhub".
```
	if config.Registry == "alicloud" {
		alicloudFullName, fullnameOk := repository.(map[string]interface{})["repo_full_name"].(string)
		alicloudRegion, regionOk := repository.(map[string]interface{})["region"].(string)
		if fullnameOk && regionOk {
			imageName := "registry." + alicloudRegion + ".aliyuncs.com/" + alicloudFullName
			pushedImage = imageName + ":" + pushedTag
		} else {
			return http.StatusBadRequest, fmt.Errorf("Alicloud Docker Hub response provided without image name")
		}
	} else {
		imageName, ok := repository.(map[string]interface{})["repo_name"].(string)
		if !ok {
			return http.StatusBadRequest, fmt.Errorf("Response provided without image name")
		}
		pushedImage = imageName + ":" + pushedTag
	}
```

**Comment by loganhz** [comment]
@niusmallnan updated thanks

**Comment by yasker** [comment]
@cjellick Can you check if it makes sense?

**Comment by cjellick** [comment]
@loganhz can you post a full sample of what the payload from alicloud docker hub webhook looks like?
Want to understand exactly how it differs from https://docs.docker.com/docker-hub/webhooks/

**Comment by loganhz** [comment]
thanks @cjellick 

the payload for `registry.cn-hangzhou.aliyuncs.com/logan/alpine:latest` is following:

{
  "push_data": {
    "digest": "sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe",
    "pushed_at": "2017-06-28 19:29:29",
    "tag": "latest"
  },
  "repository": {
    "date_created": "2017-06-28 18:48:05",
    "name": "alpine",
    "namespace": "logan",
    "region": "cn-hangzhou",
    "repo_authentication_type": "NO_CERTIFIED",
    "repo_full_name": "logan/alpine",
    "repo_origin_type": "NO_CERTIFIED",
    "repo_type": "PUBLIC"
  }
}

**Comment by yasker** [comment]
@loganhz 

Can you check if we can get some URL from the request header? Probably we can get Aliyun's URL in it then we can process it internally without user specify options.

Also, @vincent99 suggested that we should call the option `PayloadFormat` rather than `Registry`since there are others registries uses the same format as Docker.

**Comment by loganhz** [comment]
@yasker  

it seems there is no header we can use in request from aliyun

{ 'content-type': 'application/json',
  'content-length': '387',
  host: 'www.cnrancher.com:8000',
  'user-agent': 'Apache-HttpClient/4.5 (Java 1.5 minimum; Java/1.8.0_92)',
  'accept-encoding': 'gzip,deflate',
  via: '1.1 iZ23hg2asndZ (squid/3.3.8)',
  'x-forwarded-for': '106.11.225.127',
  'cache-control': 'max-age=259200',
  connection: 'keep-alive' }

**Comment by yasker** [comment]
Thanks @loganhz , seems we still need the payload format entry then.

**Comment by loganhz** [comment]
@yasker done

**Comment by yasker** [comment]
@vincent99

How does it look now?

**Comment by cjellick** [comment]
Can you make the new field an enumeration so that we can control what the user inputs? Here's an example:
https://github.com/rancher/webhook-service/blob/master/drivers/scale_host.go#L459-L483

Test it by hitting the `/v1-webhooks/schemas` endpoint, find the appropriate resource and examining its schema to ensure the field is configured as an enum.

**Comment by loganhz** [comment]
@cjellick done. 
Now UI shows the payload format options defined in backend.
But I guess only service upgrade is using the webhook schema.
The options and default value for scale host and service are hard code in UI side.

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
